# Generated by Django 4.0.5 on 2022-06-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('addres', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
    ]
